version: '3'
services:
  app:
    container_name: docker-mongo-node
    restart: always
    build: .
    ports:
      - '70:3000'
    links:
      - mongo
  mongo:
    container_name: mongo 
    image: mongo
    ports:
     - '27017:27017'   